web/Web.Smartway/Areas/Recepcion/Models/DocumentoRecepcionDetalleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Smartway.Areas.Recepcion.Models
{
    public class DocumentoRecepcionDetalleModel
    {
        //Necesario para la carga // No es un valor de base de datos.
        public int item { get; set; }


        public long? iddocumentorecepciondetalle { get; set; }
        public long iddocumentorecepcion { get; set; }

        public string codigoproducto { get; set; }
        public string descripcionlarga { get; set; }
        public string Tipo { get; set; }

        public string numeropallet { get; set; }
        public string caja { get; set; }
        public string ubicacion { get; set; }
        public bool repuesto { get; set; }
        public int idtipoproducto { get; set; }
        public int fila { get; set; }
        public int idproducto { get; set; }
        public string _cantidad_aux { get; set; }

        public string codigo { get; set; }
        public string modelo { get; set; }

        public int idfila { get; set; }
        public string serie { get; set; }
        public string imei { get; set; }
        public string mac { get; set; }
        public int idmodelo { get; set; }
        public int cantidad { get; set; }
        public DateTime fechahorapersonalizacion { get; set; }
        public int idusuariopersonalizacion { get; set; }
        public string pallet { get; set; }
        public string fabricante { get; set; }
        public int idalmacen { get; set; }




    }
}

web/Web.Smartway/Areas/Recepcion/Models/DocumentoRecepcionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Smartway.Areas.Recepcion.Models
{
    public class DocumentoRecepcionModel
    {
        public long? iddocumentorecepcion { get; set; }
        public string numerodocumento { get; set; }
        public string documentocliente { get; set; }
        public string dua { get; set; }
        public string numerofacturacomercial { get; set; }
        public DateTime? fechafacturacomercial { get; set; }
        public int idtiporecibo { get; set; }
        public string guiaremision { get; set; }
        public int idfabricante { get; set; }
        public int idcliente { get; set; }
        public int idpartner { get; set; }
        public int idproducto { get; set; }
        public int idorigen { get; set; }
        public bool activo { get; set; }
        public DateTime? fechahoraregistro { get; set; }

        public DateTime fechahoracargaarchivo { get; set; }
        public DateTime idusuariorecepcion { get; set; }

        public DateTime? fechahorarecepcion { get; set; }

        public int idusuarioregistro { get; set; }
        public int idsucursal { get; set; }
        public int idalmacen { get; set; }
        public string ruta { get; set; }
        public string pallet { get; set; }
        public string archivo { get; set; }

        public string documentcompra { get; set; }
        public long? idordenservicio { get; set; }

        public string TipoRecibo { get; set; }

        public string partner { get; set; }
        public string fabricante { get; set; }

        public string UsuarioRegistro { get; set; }
        public string numeroordenservicio { get; set; }
        public string Origen { get; set; }


    }
}

web/Web.Smartway/Areas/Recepcion/Models/RecepcionModel.cs
using System;

namespace Web.Smartway.Areas.Recepcion.Models
{
    public class RecepcionModel
    {
        public long idguiaremision { get; set; }
        public string numeroguia { get; set; }
        public DateTime fechaemision { get; set; }
        public int tipoDocInterno { get; set; }
        public bool recepcionFinalizadaAlmacen { get; set; }
        //public List<ListarDetalleGuiaDto> DetalleGuia { get; set; }
        //public List<ListarSobrantesGuiaDto> DetalleSobrantes { get; set; }
        public int idusuario { get; set; }
        public int idsucursalorigen { get; set; }
        public int idsucursaldestino { get; set; }


        public string numeroordenservicio { get; set; }
        public string fechainicio { get; set; }
        public string fechafin { get; set; }
        public int idestado { get; set; }
        public int idtecnico { get; set; }

        public string serie { get; set; }
    }


}

web/Web.Smartway/Areas/Recepcion/Controllers/RecepcionController.cs
using QueryContracts.Smartway.Mantenimiento.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Caching;
using System.Web.Mvc;
using Web.Common.Controllers;
using Web.Smartway.Areas.Agendamiento.Models;
using Web.Smartway.Areas.Mantenimiento.Models;
using Web.Smartway.DataAccess;
using Web.Smartway.DataAccess.Mantenimiento;
using Web.Common.HtmlHelpers;
using Web.Common.Extensions;
using System.Configuration;
using Web.Smartway.Areas.Recepcion.Models;
using Web.Smartway.DataAccess.Recepcion;
using Web.Smartway.DataAccess.Agendamiento;
using Web.Smartway.Areas.Inventario.Models;
using Web.Smartway.DataAccess.Inventario;
using System.Web;
using System.IO;
using LinqToExcel;


namespace Web.Smartway.Areas.Agendamiento.Controllers
{
    public class RecepcionController : BaseController
    {
        public ActionResult RecepcionGuias()
        {
            var sucursal = new SucursalData().ListarSucursal("", "", null);
            var listasucursal = new SelectList(
               sucursal,
               "idsucursal",
               "nombre");
            ViewData["listasucursal"] = listasucursal;

            var estado = MantenimientoData.GetListarEstado((Int32)Constantes.MaestroTablas.Programacion);
            var listadoestado = new SelectList(estado, "idestado", "estado");
            ViewData["listadoestado"] = listadoestado;



            return View();
        }

        #region SeguimientoRecepcion

        public ActionResult SeguimientoRecepcion()
        {
            return View();
        }
        public JsonResult JsonGetListarDocumentosRecepcion(String fechahorainicio
            , String fechahorafin, string numerorecepcion)
        {

            if (fechahorainicio == "") fechahorainicio = null;
            if (fechahorafin == "") fechahorafin = null;

            var listadoTotal = new RecepcionData().GetListarDocumentoRecepcion(fechahorainicio, fechahorafin, numerorecepcion).ToList();
            var resjson1 = (new JqGridExtension<DocumentoRecepcionModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;

        }
        public JsonResult JsonGetListarDocumentosRecepcionDetalle(long iddocumentorecepcion)
        {
       
            var listadoTotal = new RecepcionData().GetListarDocumentoRecepcionDetalle(iddocumentorecepcion).ToList();
            var resjson1 = (new JqGridExtension<DocumentoRecepcionDetalleModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;

        }
        #endregion
        public ActionResult RecepcionOrdenServicio(int id)
        {
            Session["GuiaDetalle"] = null;


            var guia = new DespachoData().obtenerGuiaRemision(id);


            var modRecepcion = new RecepcionModel();
            modRecepcion.recepcionFinalizadaAlmacen = false;
            modRecepcion.numeroguia = guia.numeroguia;
            modRecepcion.idsucursaldestino = guia.idsucursaldestino;
            modRecepcion.idsucursalorigen = guia.idsucursalorigen;
            modRecepcion.idguiaremision = id;

            var sucursal = new SucursalData().ListarSucursal("", "", null);
            var listasucursal = new SelectList(
               sucursal,
               "idsucursal",
               "nombre");
            ViewData["listasucursal"] = listasucursal;





            return View(modRecepcion);
        }
        public JsonResult JsonGetListarGuias(int? idsucursaldestino, int? idsucursalorigen
               , string sord
            , int page
            , int rows)
        {
            var listadoTotal = new DespachoData().GetListarGuia(32, idsucursaldestino, idsucursalorigen).ToList();
            var resjson1 = (new JqGridExtension<GuiaRemisionModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;
        }
        public JsonResult JsonGetListarOrdenServicio(int idguiaremision)
        {

            List<OrdenServicioModel> listadoTotal;

            if (Session["GuiaDetalle"] != null)
                listadoTotal = (List<OrdenServicioModel>)Session["GuiaDetalle"];
            else
                listadoTotal = new RecepcionData().GetListarOrdenServicio(idguiaremision).ToList();


            Session["GuiaDetalle"] = listadoTotal;

            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

            if (sortColumn != "" && sortColumnDir != "")
            {
                if (sortColumnDir.ToUpper() == "DESC")
                {
                    var parametro = sortColumn;
                    var propertyInfo = typeof(OrdenServicioModel).GetProperty(parametro);
                    listadoTotal = listadoTotal.OrderByDescending(x => propertyInfo.GetValue(x, null)).ToList();
                }
                else
                {
                    var parametro = sortColumn;
                    var propertyInfo = typeof(OrdenServicioModel).GetProperty(parametro);
                    listadoTotal = listadoTotal.OrderBy(x => propertyInfo.GetValue(x, null)).ToList();
                }
            }
            var displayedDocumentos = listadoTotal;
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;
            recordsTotal = displayedDocumentos.Count();
            var data = displayedDocumentos.Skip(skip).Take(pageSize).ToList();
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult RecepcionarDocumentoAgregadoAlmacen(string documento)
        {
            try
            {
                bool requiereImei = false;
                if (Session["GuiaDetalle"] != null)
                {
                    var ListaDetalle = (List<OrdenServicioModel>)Session["GuiaDetalle"];

                    var DocumentoBusqueda = ListaDetalle.Where(x =>
                    x.numeroordenservicio == documento).SingleOrDefault();
                    DocumentoBusqueda.requiereimei = true;
                    if (DocumentoBusqueda != null)
                    {
                        DocumentoBusqueda.documento_coincide = true;
                        if (DocumentoBusqueda.requiereimei == false)
                        {
                            DocumentoBusqueda.recepciondestino = true;
                            requiereImei = DocumentoBusqueda.requiereimei;
                        }
                        else
                        {
                            DocumentoBusqueda.recepciondestino = false;
                            requiereImei = DocumentoBusqueda.requiereimei;
                        }
                    }
                    else
                    {
                        //string tipoDocumento = "";
                        //if (documento.Length > 3) { tipoDocumento = documento.Substring(0, 3); }

                        //var Existe = IncidenciasData.ValidarDocumentoInterno(tipoDocumento, documento);

                        //if (Existe.existe > 0)
                        //{
                        //    var DatosSobrante = IncidenciasData.ObtenerDocumentoInterno(tipoDocumento, documento);

                        //    if (DatosSobrante != null)
                        //    {
                        //        var ListaSobrantes = (List<ListarDetalleGuiaDto>)Session[SESSION_DETALLE_SOBRANTES];

                        //        ListarDetalleGuiaDto Sobrante = new ListarDetalleGuiaDto();
                        //        Sobrante.inc_int_id = DatosSobrante.inc_int_id;
                        //        Sobrante.dci_int_id = DatosSobrante.dci_int_id;
                        //        Sobrante.documento_interno = DatosSobrante.numero;
                        //        Sobrante.pro_str_codigo = DatosSobrante.pro_str_codigo;
                        //        Sobrante.pro_str_descripcion = DatosSobrante.pro_str_descripcion;
                        //        Sobrante.pro_str_serieimei = DatosSobrante.pro_str_serieimei;

                        //        ListaSobrantes.Add(Sobrante);
                        //        Session[GuiaDetalle] = ListaSobrantes;
                        //    }
                        //}





                    }

                    Session["GuiaDetalle"] = ListaDetalle;
                }

                return Json(new { res = true, imei = requiereImei }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { res = false, imei = false }, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult ConfirmarIMEIDocumentoAgregadoAlmacen(string imei)
        {
            try
            {
                if (Session["GuiaDetalle"] != null)
                {
                    var ListaDetalle = (List<OrdenServicioModel>)Session["GuiaDetalle"];

                    foreach (var detalle in ListaDetalle)
                    {
                        if (detalle.serie == imei && detalle.documento_coincide == true && detalle.requiereimei == true)
                        {
                            detalle.recepciondestino = true;
                            detalle.documento_coincide = true;
                            detalle.imei_coincide = true;
                            detalle.imei_escaneado = imei;

web/Web.Smartway/Areas/Recepcion/Views/Recepcion/RecepcionGuias.cshtml
@model  Web.Smartway.Areas.Agendamiento.Models.GuiaRemisionModel
@{
    ViewBag.Title = "Recepción de Guías";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Styles
    {

    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jqGrid/ui.jqgrid.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jqgrid.extension.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jasny/jasny-bootstrap.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/sweetalert/sweetalert.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/touchspin/jquery.bootstrap-touchspin.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/chosen/chosen.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/application.css")" />


}
@section scripts
    {
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/app/Recepcion/recepcion.recepcionguias.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/jquery.jqGrid.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/i18n/grid.locale-es.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/datapicker/bootstrap-datepicker.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jasny/jasny-bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/sweetalert/sweetalert.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/t  ouchspin/jquery.bootstrap-touchspin.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/chosen/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/MetroJS/release/MetroJs.Full/MetroJs.js")" type="text/javascript"></script>
}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-5">
            <h2>Seguimiento de Incidencias</h2>
            <ol class="breadcrumb">

                <li class="active">
                    <strong>@ViewBag.Title</strong>
                </li>
                <li>
                    <a href="@Url.Action("NuevoProducto", "Mantenimiento")">Nueva Incidencia</a>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row ">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><i class="fa fa-info-circle"></i>  Filtro de búsqueda</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="control-label col-md-1">Origen:</label>
                                <div class="col-md-3">
                                    @Html.DropDownListFor(m => m.idsucursalorigen, (SelectList)ViewData["listasucursal"], "--Todos--", new { @class = "form-control input-sm", @required = "true" })
                                </div>
                                <label class="control-label col-md-1">N° Guía:</label>
                                <div class="col-md-3">
                                    @Html.DropDownListFor(m => m.numeroguia, (SelectList)ViewData["listasucursal"], "--Todos--", new { @class = "form-control input-sm", @required = "true" })
                                </div>
                                <label class="col-md-1 control-label"> Estado  :</label>
                                <div class="col-md-2">
                                    @Html.DropDownListFor(x => x.idestado, (SelectList)ViewData["listadoestado"], "--Todos--", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">

                                <label class="col-md-1 control-label">Fecha Inicio:</label>
                                <div class="col-md-2" id="data_1">
                                    <div class="input-group date" id='dtpFechInicio'>
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        @Html.TextBoxFor(model => model.fechainicio, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                    </div>
                                </div>
                                <label class="col-md-2  control-label">Fecha Fin:</label>
                                <div class="col-md-2" id="data_2">
                                    <div class="input-group date" id='dtpFechFin'>
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        @Html.TextBoxFor(model => model.fechafin, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                    </div>
                                </div>
                           
                            </div>
                            <div class="form-group">
                                <div class="col-md-2 col-md-offset-9">
                                    <button type="button" id='btnBuscar' class="btn  btn-line btn-block btn-sm btn-primary"><i class="fa fa-search"></i> Buscar </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>


        <div class="row ">
            <div class="col-md-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><i class="fa fa-info-circle"></i>  Listado de Guías de Remisión</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>

                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="jqGrid_wrapper col-md-12">
                                    <table id="gridguias"
                                           data-dataurl="@Url.Action("JsonGetListarGuias", "Recepcion")"></table>
                                    <div id="gridguiaspager"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

web/Web.Smartway/Areas/Recepcion/Views/Recepcion/SeguimientoRecepcion.cshtml
@model  Web.Smartway.Areas.Agendamiento.Models.OrdenServicioModel
@{
    ViewBag.Title = "Seguimiento Recepción";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Styles
    {

    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jqGrid/ui.jqgrid.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jqgrid.extension.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jasny/jasny-bootstrap.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/sweetalert/sweetalert.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/touchspin/jquery.bootstrap-touchspin.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/chosen/chosen.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/application.css")" />


}
@section scripts
    {
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/app/Recepcion/recepcion.seguimientorecepcion.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/jquery.jqGrid.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/i18n/grid.locale-es.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/datapicker/bootstrap-datepicker.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jasny/jasny-bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/sweetalert/sweetalert.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/touchspin/jquery.bootstrap-touchspin.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/chosen/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/MetroJS/release/MetroJs.Full/MetroJs.js")" type="text/javascript"></script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-5">
        <h2>Panel de Recepción</h2>
        <ol class="breadcrumb">

            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>

        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row ">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Filtro de búsqueda</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            @*<div class="col-md-4">
                                    <label class="control-label"> Tipo</label>
                                    @Html.DropDownListFor(x => x.idtipoordenservicio, (SelectList)ViewData["listadotipoorden"], "--Todos--", new { @class = "form-control" })
                                </div>*@
                            <div class="col-md-3" id="data_1">
                                <label class="control-label">Fecha Inicio</label>
                                <div class="input-group date" id='dtpFechInicio'>
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.TextBoxFor(model => model.fechahorainicio, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-3" id="data_2">
                                <label class="control-label">Fecha Fin</label>
                                <div class="input-group date" id='dtpFechFin'>
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.TextBoxFor(model => model.fechahorafin, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label">N° Recepción</label>
                                @Html.TextBoxFor(x => x.numeroordenservicio, new { @class = "form-control" })
                            </div>

                            <div class="col-md-2">
                                <label class="control-label"></label>
                                <button type="button" id='btnBuscar' class="btn  btn-line btn-block btn-sm btn-primary"><i class="fa fa-search"></i> Buscar </button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Recepciones</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>

                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="jqGrid_wrapper col-md-12">
                                <table id="gridordenes"
                                       data-dataurl="@Url.Action("JsonGetListarDocumentosRecepcion", "Recepcion")"></table>
                                <div id="gridordenespager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Recepciones Detalle</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>

                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="jqGrid_wrapper col-md-12">
                                <table id="gridordenesdetalle"
                                       data-dataurl="@Url.Action("JsonGetListarDocumentosRecepcionDetalle", "Recepcion")"></table>
                                <div id="gridordenesdetallepager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

web/Web.Smartway/Areas/Recepcion/Views/Recepcion/_UploadFile.cshtml
@model  Web.Smartway.Areas.Recepcion.Models.DocumentoRecepcionModel
@{

}
<form id="frmDocumentacion" role="form" method="post" action="@Url.Action("SubirArchivo", "Recepcion")" class="form-horizontal" enctype="multipart/form-data">
    @*@using (Ajax.BeginForm("SubirArchivo", "Liquidacion", new { area = "Liquidacion" }, new AjaxOptions { HttpMethod = "POST", OnComplete = "OnCompleteTransaction(xhr, status)" }, new { enctype = "multipart/form-data", @role = "form", @id = "frmDocumentacion", @class = "form-horizontal" }))*@

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        @*<i class="fa fa-users fa-4x"></i>*@
        <h4 class="modal-title">Cargar Excel</h4>
        <small class="font-bold">Digitar los datos necesarios para el registro masivo</small>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-2 control-label">Archivo:</label>
                    <div class="col-md-10">@Html.TextBoxFor(model => model.archivo, "", new { @class = "form-control", @type = "file" })</div>
                </div>
                <div class="form-group">
                    <input value="La extensión no está permitida" class="col-md-12 alert alert-danger" type="text" id="error" />
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        @*@Html.HiddenFor(x => x.idorden)*@
        <button type="submit" class="btn  btn-line btn-primary"><i class="fa fa-upload"></i> Subir Archivo </button>
        <button type="button" class="btn  btn-outline btn-danger btn-sm" data-dismiss="modal"><i class="fa fa-times-circle-o"></i>  Cerrar</button>
    </div>
</form>