web/Web.Smartway/Areas/Guias/Controllers/GuiasController.cs
using System.Web.Mvc;
using Web.Common.Controllers;
using Web.Smartway.DataAccess;
using Web.Smartway.DataAccess.Mantenimiento;
using System.Linq;
using Web.Smartway.Areas.Despacho.Models;
using Web.Common.Extensions;
using Web.Smartway.Areas.Agendamiento.Models;

namespace Web.Smartway.Areas.Guias.Controllers
{
    public class GuiasController : BaseController
    {
        public ActionResult ListarGuias()
        {
            var sucursal = new SucursalData().ListarSucursal("", "", null, Usuario.idpartner);
            var listasucursal = new SelectList(
               sucursal,
               "idsucursal",
               "nombre");
            ViewData["listasucursal"] = listasucursal;

            return View();
        }
       
        public PartialViewResult NuevaGuia()
        {
            var sucursal = new SucursalData().ListarSucursal("", "", null, Usuario.idpartner);
            var listasucursal = new SelectList(
               sucursal,
               "idsucursal",
               "nombre");
            ViewData["listasucursal"] = listasucursal;

            var clientes = MantenimientoData.GetListarClientes(null, true).ToList();
            var listaclientes = new SelectList(
                   clientes,
                   "idcliente",
                   "nombre");
            ViewData["ListadoClientes"] = listaclientes;

            var transportista = new DespachoData().GetListarTransportista();
            var listadotransportista = new SelectList(transportista, "idtransportista", "razonsocial");
            ViewData["listadotransportista"] = listadotransportista;


            return PartialView("_NuevaGuiaRemision");

        }
        public PartialViewResult NuevoDetalleGuia(long id)
        {

            var model = new GuiaRemisionDetalleModel();
            model.idguiaremision = id;

            return PartialView("_NuevoDetalleGuia", model);

        }
        [HttpPost]
        public JsonResult InsertarActualizarGuiaRemision(GuiaRemisionDetalleModel guiadetalle)
        {
            OrdenSalidaModel orden = null;
            if (guiadetalle.numeroordensalida != null)
                orden = new DespachoData().GetListarOrdenSalida(guiadetalle.numeroordensalida.Trim()).SingleOrDefault();

            if (orden != null)
            {
                var detalles = new DespachoData().GetListarOrdenSalidaDetalle(orden.iddocumentosalida.Value).ToList();
                GuiaRemisionDetalleModel Newguiadetalle = null;

                foreach (var item in detalles)
                {
                    Newguiadetalle = new GuiaRemisionDetalleModel();
                    Newguiadetalle.cantidad = detalles.Count;
                    Newguiadetalle.codigo = item.codigoproducto; 
                    Newguiadetalle.descripcion = item.descripcionlarga;            
                    Newguiadetalle.idguiaremision = guiadetalle.idguiaremision;


                    new DespachoData().InsertarActualizarGuiaRemisionDetalle(Newguiadetalle);
                    break;
                }
            }
            else
            {
                new DespachoData().InsertarActualizarGuiaRemisionDetalle(guiadetalle);
            }

            return Json(new { res = true });
        }


        [HttpPost]
        public JsonResult GenerarGuiaRemision(ProgramacionModel model)
        {
            
            

            GuiaRemisionModel modGuia = new GuiaRemisionModel();
            modGuia.direcciondestino = model.direcciondestino;
            modGuia.direccionorigen = model.direccionorigen;
            modGuia.fechaguiaremision = model.fechaemision;
            modGuia.numeroguia = model.numeroguia;
            modGuia.iddestinatario = model.iddestinatario;
            modGuia.idusuarioregistro = Usuario.Idusuario;
            modGuia.idtransportista = model.idtransportista;
            

            modGuia.direcciondestino = model.direcciondestino;
            modGuia.direccionorigen = model.direccionorigen;

            modGuia.idestado = (int)Constantes.EstadoGuiaRemision.Despachado;
            modGuia.__tipooperacion = 1;
            var idguia = new DespachoData().InsertarActualizarGuiaRemision(modGuia);

        
            return Json(new { res = true });

        }
        [HttpPost]
        public JsonResult JsonGetListarGuias(int? idsucursaldestino, int? idsucursalorigen)
        {
            var listadoTotal = new DespachoData().GetListarGuia(null, null, null).ToList();
            var resjson1 = (new JqGridExtension<GuiaRemisionModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;
        }
        [HttpPost]
        public JsonResult JsonGetListarGuiaDetalles(long idguiaremision)
        {
            var listadoTotal = new DespachoData().GetListarGuiaDetalle(idguiaremision).ToList();
            var resjson1 = (new JqGridExtension<GuiaRemisionDetalleModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;
        }
        [HttpPost]
        public JsonResult EliminarDetalleGuia(long iddetalle)
        {
            new DespachoData().EliminarDetalleGuia(iddetalle);
            return Json(new { res = true });
        }
    }
}

web/Web.Smartway/Areas/Guias/Views/Guias/ListarGuias.cshtml
@model  Web.Smartway.Areas.Despacho.Models.ProgramacionModel
@{
    ViewBag.Title = "Listar Guías de Remisión";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles
    {

    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jqGrid/ui.jqgrid.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jqgrid.extension.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jasny/jasny-bootstrap.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/sweetalert/sweetalert.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/touchspin/jquery.bootstrap-touchspin.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/chosen/chosen.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/application.css")" />
}
@section scripts
    {
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/app/jquery.mask.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/app/guias/Guias.listadoguias.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/jquery.jqGrid.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/i18n/grid.locale-es.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/datapicker/bootstrap-datepicker.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jasny/jasny-bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/sweetalert/sweetalert.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/touchspin/jquery.bootstrap-touchspin.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/chosen/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/MetroJS/release/MetroJs.Full/MetroJs.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/dualListBox/jquery.bootstrap-duallistbox.js")" type="text/javascript"></script>}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-5">
        <h2>Listar Guias</h2>
        <ol class="breadcrumb">

            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>

        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row ">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Filtro de búsqueda</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-1">Origen:</label>
                            <div class="col-md-3">
                                @Html.DropDownListFor(m => m.search_idsucursalorigen, (SelectList)ViewData["listasucursal"], "--Todos--", new { @class = "form-control input-sm", @required = "true" })
                            </div>
                            <label class="control-label col-md-1">Destino:</label>
                            <div class="col-md-3">
                                @Html.DropDownListFor(m => m.search_idsucursaldestino, (SelectList)ViewData["listasucursal"], "--Todos--", new { @class = "form-control input-sm", @required = "true" })
                            </div>
                            @*<label class="col-md-1 control-label"> Estado  :</label>
                                <div class="col-md-2">
                                    @Html.DropDownListFor(x => x.idestado, (SelectList)ViewData["listadoestado"], "--Todos--", new { @class = "form-control" })
                                </div>*@
                        </div>
                        <div class="form-group">

                            <label class="col-md-1 control-label">Fecha Inicio:</label>
                            <div class="col-md-2" id="data_1">
                                <div class="input-group date" id='dtpFechInicio'>
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.TextBoxFor(model => model.fechainicio, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                </div>
                            </div>
                            <label class="col-md-2  control-label">Fecha Fin:</label>
                            <div class="col-md-2" id="data_2">
                                <div class="input-group date" id='dtpFechFin'>
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.TextBoxFor(model => model.fechafin, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-2 col-md-offset-9">
                                <button type="button" id='btnBuscar' class="btn  btn-line btn-block btn-sm btn-primary"><i class="fa fa-search"></i> Buscar </button>
                                @Html.Hidden("iddetallebusqueda")
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="row ">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Listado de Despachos Programados</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>

                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-2">
                                <button type="button" id='btnNuevo' class="btn  btn-line btn-block btn-sm btn-primary"><i class="fa fa-plus"></i> Nueva Guía </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="jqGrid_wrapper col-md-12">
                                <table id="gridguias"
                                       data-dataurl="@Url.Action("JsonGetListarGuias", "Guias")"></table>
                                <div id="gridguiaspager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Recepciones Detalle</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>

                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="jqGrid_wrapper col-md-12">
                                <table id="griddetalle"
                                       data-dataurl="@Url.Action("JsonGetListarGuiaDetalles", "Guias")"></table>
                                <div id="gridetallepager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

web/Web.Smartway/Areas/Guias/Views/Guias/_NuevaGuiaRemision.cshtml
@model Web.Smartway.Areas.Despacho.Models.ProgramacionModel
@section Styles {
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jqGrid/ui.jqgrid.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jqgrid.extension.css")" />

}
@using (Ajax.BeginForm("GenerarGuiaRemision", "Guias", null, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "modalcontent", OnComplete = "OnCompleteTransaction(xhr, status)" }, new { @class = "form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Agregar cabecera de Guía</h4>
        <small class="font-bold">Ingresar todos los datos requeridos</small>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label">Número de Guía de Remisión:</label>
                        @Html.TextBoxFor(x => x.numeroguia, new { @class = "form-control", @required = "true" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label">Origen:</label>
                        @Html.TextBoxFor(x => x.direccionorigen, new { @class = "form-control", @required = "true" })
                    </div>
                    <div class="col-md-5">
                        <label class="control-label">Destino:</label>
                        @Html.TextBoxFor(x => x.direcciondestino, new { @class = "form-control", @required = "true" })
                    </div>

                </div>
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label">Destinatario:</label>
                        @Html.DropDownListFor(model => model.iddestinatario, (SelectList)ViewData["ListadoClientes"], "-- Seleccionar --", new { @class = "chosen-select form-control", @required = "true" })

                    </div>
                    <div class="col-md-5">
                        <label class="control-label">Transportista:</label>
                        @Html.DropDownListFor(model => model.idtransportista, (SelectList)ViewData["listadotransportista"], "-- Seleccionar --", new { @class = "chosen-select form-control", @required = "true" })

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label">F. de Emisión:</label>
                        <div id="data_3">
                            <div class="input-group date" id='dtpFechEmision'>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                @Html.TextBoxFor(model => model.fechaemision, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    @*<div class="col-md-5">
                        <label class="control-label">Nro Despacho:</label>
                        @Html.TextBoxFor(x => x.numeroordensalida, new { @class = "form-control"})
                    </div>*@
                </div>  
                </div>


            </div>
    </div>
    <div class="modal-footer">
        <div class="col-md-3">
            <button type="submit" class="btn btn-block btn-primary btn-sm"><i class="fa fa-bus"></i> Generar </button>  
        </div>
    </div>

}
@*<div class="hr-line-dashed"></div>*@

web/Web.Smartway/Areas/Guias/Views/Guias/_NuevoDetalleGuia.cshtml
@model Web.Smartway.Areas.Agendamiento.Models.GuiaRemisionDetalleModel
@section Styles {
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jqGrid/ui.jqgrid.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jqgrid.extension.css")" />

}
@using (Ajax.BeginForm("InsertarActualizarGuiaRemision", "Guias", null, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "modalcontent", OnComplete = "OnCompleteTransaction(xhr, status)" }, new { @class = "form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Detalle de guía</h4>
        <small class="font-bold">Ingresar detalle de la guía</small>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label">Nro Despacho:</label>
                        @Html.TextBoxFor(x => x.numeroordensalida, new { @class = "form-control" })
                    </div>
                    <div class="col-md-5">
                        <label class="control-label">Código (N° OST):</label>
                        @Html.TextBoxFor(x => x.codigo, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <label class="control-label">Descripción:</label>
                        @Html.TextAreaFor(x => x.descripcion, new {
                       TextMode = "MultiLine",
                       Columns = "50",
                       Rows = "5",
                       @class = "form-control" })
                    </div>


                </div>
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label">Cantidad:</label>
                        @Html.TextBoxFor(x => x.cantidad, new { @class = "form-control" })
                        
                    </div>
                </div>


            </div>

        </div>
    </div>
    <div class="modal-footer">
        <div class="col-md-3">
            <button type="submit" class="btn btn-block btn-primary btn-sm"><i class="fa fa-bus"></i> Guardar </button>
        </div>
    </div>
    @Html.HiddenFor(x=>x.idguiaremision)
    @Html.HiddenFor(x=>x.idordenservicio)
}
@*<div class="hr-line-dashed"></div>*@