web/Web.Smartway/Areas/Despacho/Models/OrdenSalidaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Smartway.Areas.Despacho.Models
{
    public class OrdenSalidaModel
    {
        public long? iddocumentosalida { get; set; }
        public string numerodocumento { get; set; }
        public int idcliente { get; set; }
        public int idtiposalida { get; set; }
        public bool activo { get; set; }
        public int idproducto { get; set; }
        public DateTime fechahoraregistro { get; set; }
        public DateTime fechasalida { get; set; }
        public int idusuarioregistro { get; set; }
        public string archivo { get; set; }
        public string lote { get; set; }
        public IEnumerable<OrdenSalidaDetalleModel> detalles { get; set; }
        

    }
    public class OrdenSalidaDetalleModel 
    {
        public long idordensalidadetalle { get; set; }
        public int item { get; set; }
        public long idordensalida { get; set; }
        public long idordenservicio { get; set; }
        public string codigo { get; set; }
        public int idproducto { get; set; }
        public int cantidad { get; set; }
        public string serie { get; set; }
        public string imei { get; set; }
        public string mac { get; set; }
        public DateTime fechahoraatencion { get; set; }
        public int idusuarioatencion { get; set; }
        public bool repuesto { get; set; }
        public long idinventario { get; set; }
        public string codigoproducto { get; set; }
        public string descripcionlarga { get; set; }
    }
}

web/Web.Smartway/Areas/Despacho/Models/ProgramacionModel.cs
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Smartway.Areas.Despacho.Models
{

    public class ProgramacionDetalleModel
    {
        public int? idprogramaciondetalle { get; set; }
        public int idprogramacion { get; set; }
        public int idguia { get; set; }
    }
    public class ProgramacionModel
    {
        public int search_idsucursalorigen { get; set; }
        public int search_idsucursaldestino { get; set; }

        public int searchmodal_idsucursalorigen { get; set; }
        public int searchmodal_idsucursaldestino { get; set; }

        public string direccionorigen { get; set; }
        public string direcciondestino { get; set; }
        public string numeroguia { get; set; }
        public int iddestinatario { get; set; }

        public int? idprogramacion { get; set; }
        public string numero { get; set; }
        public string sucursalorigen { get; set; }
        public string sucursaldestino { get; set; }
        public string razonsocial { get; set; }
        public DateTime? fecharecojo { get; set; }
        public string usuarioprogramacion { get; set; }
        public string estado { get; set; }
        public int idestado { get; set; }
        public int idtransportista { get; set; }
        public DateTime fechahoraregistro { get; set; }

        public DateTime fechainicio { get; set; }
        public DateTime fechafin { get; set; }

        public DateTime fechaemision { get; set; }

        public int idsucursalorigen { get; set; }
        public int idsucursaldestino { get; set; }
        public int idusuarioregistro { get; set; }
        public long? idordensalida { get; set; }
        public string numeroordensalida { get; set; }

        public int __tipooperacion { get; set; }
    }
    
}

web/Web.Smartway/Areas/Despacho/Controllers/DespachoController.cs
using QueryContracts.Smartway.Mantenimiento.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Caching;
using System.Web.Mvc;
using Web.Common.Controllers;
using Web.Smartway.Areas.Agendamiento.Models;
using Web.Smartway.Areas.Mantenimiento.Models;
using Web.Smartway.DataAccess;
using Web.Smartway.DataAccess.Mantenimiento;
using Web.Common.HtmlHelpers;
using Web.Common.Extensions;
using System.Configuration;
using Web.Smartway.Areas.Despacho.Models;
using Web.Smartway.DataAccess.Recepcion;
using Web.Smartway.DataAccess.Agendamiento;
using System.Web;
using System.IO;
using LinqToExcel;
using Web.Smartway.DataAccess.Inventario;
using Web.Smartway.Areas.Inventario.Models;

namespace Web.Smartway.Areas.Agendamiento.Controllers
{
    public class DespachoController : BaseController
    {

        public ActionResult SeguimientoDespacho() { return View(); }
        public JsonResult JsonGetListarDocumentosDespacho(String fechahorainicio
           , String fechahorafin, string numerorecepcion)
        {

            

            var listadoTotal = new DespachoData().GetListarOrdenSalida(null).ToList();
            var resjson1 = (new JqGridExtension<OrdenSalidaModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;

        }


        public ActionResult ProgramarDespacho()
        {
            var sucursal = new SucursalData().ListarSucursal("", "", null);
            var listasucursal = new SelectList(
               sucursal,
               "idsucursal",
               "nombre");
            ViewData["listasucursal"] = listasucursal;

            
            var estado = MantenimientoData.GetListarEstado((Int32)Constantes.MaestroTablas.Programacion);
            var listadoestado = new SelectList(estado, "idestado", "estado");
            ViewData["listadoestado"] = listadoestado;




            var transportista = new DespachoData().GetListarTransportista();
            var listadotransportista = new SelectList(transportista, "idtransportista", "razonsocial");
            ViewData["listadotransportista"] = listadotransportista;



            return View();
        }
        [HttpPost]
        public JsonResult JsonGetListarProgramacion(int? idsucursalorigen
            , int? idsucursaldestino
            , int? idestado
            , string fechainicio
            , string fechafin)
        {

            if (fechafin == "")
                fechafin = null;
            if (fechainicio == "")
                fechainicio = null;

            var listadoTotal = DespachoData.GetListarProgramacion(idsucursalorigen
                ,idsucursaldestino
                ,idestado
                ,fechainicio
                ,fechafin).ToList();
            var resjson1 = (new JqGridExtension<ProgramacionModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;
        }


        public PartialViewResult ProgramarGuiasModal()
        {
            var sucursal = new SucursalData().ListarSucursal("", "", null);
            var listasucursal = new SelectList(
               sucursal,
               "idsucursal",
               "nombre");
            ViewData["listasucursal"] = listasucursal;

            var transportista = new DespachoData().GetListarTransportista();
            var listadotransportista = new SelectList(transportista, "idtransportista", "razonsocial");
            ViewData["listadotransportista"] = listadotransportista;

            var modProgramar = new ProgramacionModel();
            return PartialView("_ProgramarGuiasModal", modProgramar);
        }
        public JsonResult JsonGetListarGuias ( int? idsucursaldestino, int? idsucursalorigen 
               , string sord
            , int page
            , int rows)
        {
            var listadoTotal = new DespachoData().GetListarGuia(31,idsucursaldestino,idsucursalorigen).ToList();
            var resjson1 = (new JqGridExtension<GuiaRemisionModel>()).DataBind(listadoTotal, listadoTotal.Count);
            return resjson1;
        }
        [HttpPost]
        public JsonResult JsonGenerarDespacho(string ids, DateTime? fecharecojo, int? idtransporte)
        {
            string[] guias = ids.Split(',');
            var modGuiaAct = new GuiaRemisionModel();
            //var modGuiaAct = new GuiaRemisionModel();
            //modGuiaAct.


            foreach (var item in guias)
            {

                var guia = new DespachoData().obtenerGuiaRemision(Convert.ToInt64(item));
                var osts = new RecepcionData().GetListarOrdenServicio(Convert.ToInt32(item));

                foreach (var item1 in osts)
                {
                    var modOrdenServicio = new OrdenServicioModel();
                    modOrdenServicio.idordenserviciotecnico = item1.idordenserviciotecnico;
                    modOrdenServicio.__tipooperacion = 2; // actualizar estado
                    modOrdenServicio.idestado = (Int32)Constantes.EstadoOrdenServicio.PendienteRecojoDelivery;

                    new OrdenServicioData().InsertarActualizarOrdenServicio(modOrdenServicio);
                }
               


            }


            var modGuiaRemision =new DespachoData().obtenerGuiaRemision(Convert.ToInt64(guias[0]));


            var modProgramacion = new ProgramacionModel();
            modProgramacion.idestado = (Int32)(Constantes.EstadoDespacho.programada);
            modProgramacion.fechahoraregistro = DateTime.Now;
            modProgramacion.fecharecojo = fecharecojo;
            modProgramacion.idtransportista = idtransporte.Value;
            modProgramacion.idsucursalorigen = modGuiaRemision.idsucursalorigen;
            modProgramacion.idsucursaldestino = modGuiaRemision.idsucursaldestino;
            modProgramacion.idusuarioregistro = Usuario.Idusuario;
            modProgramacion.numero = "100-000001";
            modProgramacion.__tipooperacion = 1;

            var res = new DespachoData().InsertarActualizarProgramacion(modProgramacion);


            var modProgramacionDetalle = new ProgramacionDetalleModel();

            foreach (var item in guias)
            {

                modGuiaAct = new DespachoData().obtenerGuiaRemision(Convert.ToInt64(item));
                modGuiaAct.idestado = (Int32) Constantes.EstadoGuiaRemision.Programada;
                modGuiaAct.__tipooperacion = 2;
                new DespachoData().InsertarActualizarGuiaRemision(modGuiaAct);

                modProgramacionDetalle = new ProgramacionDetalleModel();
                modProgramacionDetalle.idguia = Convert.ToInt32(item);
                modProgramacionDetalle.idprogramacion = res;

                var resdetalle = new DespachoData().InsertarActualizarProgramacionDetalle(modProgramacionDetalle);
            }


           
            return Json(new { res = true });
        }



        [HttpPost]
        public JsonResult DespacharGuiasDelivery(int idprogramacion)
        {
            new DespachoData().EntregarDespachoDelivery(idprogramacion);
            return Json(new { res = true });
        }



        #region despachomasivo
        public ActionResult DespachoMasivo()
        {
            var producto = new ProductoData().listarProducto("", "", null, null, null, false);
            var listaproducto = new SelectList(producto, "idproducto", "descripcionlarga");
            ViewData["listaproducto"] = listaproducto;
            Session["DespachoMasivo"] = null ;

            var orden = new OrdenSalidaModel();
            orden.fechasalida = DateTime.Now;
            return View(orden);
        }
        public PartialViewResult SubirArchivo()
        {
            OrdenSalidaModel model = new OrdenSalidaModel();
            return PartialView("_UploadFile", model);
        }
        [HttpPost]
        public JsonResult SubirArchivo(HttpPostedFileBase archivo, OrdenSalidaModel model)
        {
            string RutaArchivos = ConfigurationManager.AppSettings["Uploads"].ToString();
            string Carpeta = "File_" + Usuario.Idusuario.ToString();
            string Rutagrabar = RutaArchivos + Carpeta + "\\";
            string file = string.Empty;

            string archivo_subir = (DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + archivo.FileName).ToLower();
            archivo_subir = archivo_subir.Replace(" ", "_").ToString();

            var mod_archivo = new OrdenSalidaModel();

            var allowedExtensions = new[] { ".xlsx", ".xls" };

            var checkextension = Path.GetExtension(archivo.FileName).ToLower();

            if (!allowedExtensions.Contains(checkextension))
            {
                return Json(new { res = false, msj = "No se puede subir archivos con la extensión: " + checkextension }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                file = Rutagrabar + archivo_subir;
            }
            try
            {
                if (Directory.Exists(Rutagrabar))
                    archivo.SaveAs(file);
                else
                {
                    Directory.CreateDirectory(Rutagrabar);
                    archivo.SaveAs(file);
                }
                try
                {
                    var book = new ExcelQueryFactory(file);
                    var headers = book.GetColumnNames("Carga01");
                    var comprobar = headers.ToList();

                    if ("ITEM" != comprobar[0])
                        return Json(new { res = false, msj = "El archivo no tiene el formato establecido." });
                    if ("S/N" != comprobar[1])
                        return Json(new { res = false, msj = "El archivo no tiene el formato establecido." });
                    if ("IMEI" != comprobar[2])
                        return Json(new { res = false, msj = "El archivo no tiene el formato establecido." });
                    if ("MAC" != comprobar[3])

web/Web.Smartway/Areas/Despacho/Views/Despacho/DespachoMasivo.cshtml
@model Web.Smartway.Areas.Despacho.Models.OrdenSalidaModel

@{
    ViewBag.Title = "Recepción masiva - Orden de Reparación";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Styles
    {

    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jqGrid/ui.jqgrid.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jqgrid.extension.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/datapicker/datepicker3.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jasny/jasny-bootstrap.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/sweetalert/sweetalert.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/touchspin/jquery.bootstrap-touchspin.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/chosen/chosen.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/dataTables/datatables.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/application.css")" />
}
@section scripts
    {
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/app/Despacho/despacho.despachomasivo.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/jquery.jqGrid.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/i18n/grid.locale-es.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/datapicker/bootstrap-datepicker.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jasny/jasny-bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/sweetalert/sweetalert.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/touchspin/jquery.bootstrap-touchspin.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/chosen/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/dualListBox/jquery.bootstrap-duallistbox.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/messages_es_PE.js")" type="text/javascript"></script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Despacho Masivo - OSR</h2>
        <ol class="breadcrumb"></ol>
    </div>
    <div class="col-lg-2"></div>
</div>


@using (Ajax.BeginForm("RegistrarDespacho", "Despacho", new { area = "Despacho" }, new AjaxOptions { HttpMethod = "POST", OnComplete = "OnCompleteTransaction(xhr, status)" }, new { @role = "form", @class = "form-horizontal" }))
{
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><i class="fa fa-inbox"></i> Datos del despacho </h5>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group">
                               
                                <div class="col-md-7">
                                    <div class="panel panel-danger">
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="control-label">Fecha Despacho</label>
                                                        <div class="col-md-12" id="data_1">
                                                            <div class="input-group date" id='dtpFechInicio'>
                                                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                                @Html.TextBoxFor(model => model.fechasalida, "{0:dd/MM/yyyy}", new { @class = "form-control", @required = "true" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="control-label">Producto</label>
                                                        @Html.DropDownListFor(model => model.idproducto, (SelectList)ViewData["listaproducto"], "-- Seleccionar --", new { @class = "chosen-select form-control", @required = "true" })
                                                    </div>
                                                </div>
                                          
                                                <div class="col-md-2">
                                                    <div class="form-group">
                                                        <div class="col-md-12">
                                                            <br />
                                                            <br />
                                                            <button type="button" id="btnSelectFile" class="btn btn-warning"><i class="fa fa-recycle"></i> Subir Archivo</button>

                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p class="ImportantMessageBold" id="p_mensaje"></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><i class="fa fa-info-circle"></i>  Detalle del despacho</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="col-md-2">
                                    <button type="submit" id='btnGuardar' class="btn  btn-line btn-block btn-sm btn-primary"><i class="fa fa-plus"></i> Cargar Productos</button>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="jqGrid_wrapper col-md-12">
                                    <table id="gridcargadetalle"
                                           data-dataurl="@Url.Action("JsonListarDetalleDespacho", "Despacho")"></table>
                                    <div id="gridcargadetallepager"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

web/Web.Smartway/Areas/Despacho/Views/Despacho/ProgramarDespacho.cshtml
@model Web.Smartway.Areas.Despacho.Models.ProgramacionModel

@{
    ViewBag.Title = "Programar Despacho";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles
    {

    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jqGrid/ui.jqgrid.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jqgrid.extension.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jasny/jasny-bootstrap.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/sweetalert/sweetalert.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/touchspin/jquery.bootstrap-touchspin.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/chosen/chosen.css")" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/application.css")" />
}
@section scripts
    {
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/app/despacho/despacho.programacion.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/jquery.jqGrid.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jqGrid/i18n/grid.locale-es.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/datapicker/bootstrap-datepicker.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/jasny/jasny-bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/sweetalert/sweetalert.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/touchspin/jquery.bootstrap-touchspin.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/chosen/chosen.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/MetroJS/release/MetroJs.Full/MetroJs.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/plugins/dualListBox/jquery.bootstrap-duallistbox.js")" type="text/javascript"></script>}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-5">
        <h2>Listado de Programación</h2>
        <ol class="breadcrumb">

            <li class="active">
                <strong>@ViewBag.Title</strong>
            </li>
           
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">


    <div class="row ">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Filtro de búsqueda</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-1">Origen:</label>
                            <div class="col-md-3">
                                @Html.DropDownListFor(m => m.search_idsucursalorigen, (SelectList)ViewData["listasucursal"], "--Todos--", new { @class = "form-control input-sm", @required = "true" })
                            </div>
                            <label class="control-label col-md-1">Destino:</label>
                            <div class="col-md-3">
                                @Html.DropDownListFor(m => m.search_idsucursaldestino, (SelectList)ViewData["listasucursal"], "--Todos--", new { @class = "form-control input-sm", @required = "true" })
                            </div>
                            <label class="col-md-1 control-label"> Estado  :</label>
                            <div class="col-md-2">
                                @Html.DropDownListFor(x => x.idestado, (SelectList)ViewData["listadoestado"], "--Todos--", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">

                            <label class="col-md-1 control-label">Fecha Inicio:</label>
                            <div class="col-md-2" id="data_1">
                                <div class="input-group date" id='dtpFechInicio'>
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.TextBoxFor(model => model.fechainicio, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                </div>
                            </div>
                            <label class="col-md-2  control-label">Fecha Fin:</label>
                            <div class="col-md-2" id="data_2">
                                <div class="input-group date" id='dtpFechFin'>
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    @Html.TextBoxFor(model => model.fechafin, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                                </div>
                            </div>
                            <label class="col-md-1 col-md-offset-1 control-label"> Transportista:</label>
                            <div class="col-md-2">
                                @Html.DropDownListFor(x => x.idtransportista, (SelectList)ViewData["listadotransportista"], "--Todos--", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 col-md-offset-9">
                                <button type="button" id='btnBuscar' class="btn  btn-line btn-block btn-sm btn-primary"><i class="fa fa-search"></i> Buscar </button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


    <div class="row ">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-info-circle"></i>  Listado de Despachos Programados</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>

                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-2">
                                <button type="button" id='btnNuevo' class="btn  btn-line btn-block btn-sm btn-primary"><i class="fa fa-plus"></i> Programar Despacho </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 jqGrid_wrapper">
                                <table id="gridprogramacion"
                                       data-dataurl="@Url.Action("JsonGetListarProgramacion", "Despacho")"></table>
                                <div id="gridprogramacionpager"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>